---
- name: installing and launching beat
  hosts: 10.0.0.6
  become: yes
  tasks:

  - name: download heartbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-7.6.1-amd64.deb

  - name: install heartbeat deb
    command: sudo dpkg -i heartbeat-7.6.1-amd64.deb

  - name: drop in heartbeat.yml
    copy:
      src: /etc/heartbeat/heartbeat.yml
      dest: /etc/heartbeat/heartbeat.yml

  #- name: enable and configure system module
  #  command: sudo heartbeat modules enable system

  - name: setup filebeat
    command: sudo heartbeat setup

  - name: start heartbeat service
    command: sudo service heartbeat-elastic start

 # - name: enable service heartbeat on boot
 #   systemd:
 #     name: heartbeat
 #     enabled: yes